### ISSUE TITLE
cannot run python scholar.py : We need BeautifulSoup

### ISSUE THREAD

**Issue by rey1024** [ckreibich/scholar.py#36]
i try run 
  $python  scholar.py -c 1 --author "albert einstein" --phrase "quantum theory"
the output is : We need BeautifulSoup, sorry...

i has install BeautifulSoup ( pip install beautifulsoup)
thx for the solution :-)

**Comment by martinbetz** [comment]
Maybe the solutions is as simple as `pip install beautifulsoup4`. You might have forgotten the `4`.

**Comment by rey1024** [comment]
oh yes, i forgotten the 4. thx u so much :-)
