### ISSUE TITLE
BeautifulSoup Parser Warning

### ISSUE THREAD

**Issue by cancan101** [ckreibich/scholar.py#49]
BeautifulSoup complains:

```
/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")
```

**Comment by someValue** [comment]
/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

-------------
so
BeautifulSoup(html, 'html.parser')

**Comment by sunftec** [comment]
iam have a this problem! why?

**Comment by danwerspb** [comment]
I have it appear on the Debian 8. I am writing another script on Ubuntu 14.04.

**Comment by Ulden** [comment]
I have exactly the same problem on OS X 10.11!

**Comment by benwinding** [comment]
Also getting this issue, Ubuntu 14.04

**Comment by eknoes** [comment]
As @someValue said, you have to change line 359 
```self.soup = BeautifulSoup(html) ```
 to
```self.soup =  BeautifulSoup(html, 'html.parser') ```
Same with line 945. Remember to keep indentations

**Comment by eknoes** [comment]
You have to change the file scholar.py from this repo to get rid of this warning

**Comment by benwinding** [comment]
Thanks!

**Comment by 7sam7** [comment]
where is scholar.py?I can not find it anyway

**Comment by 7sam7** [comment]
@eknoes thank you

**Comment by lenpr** [comment]
Same problem here OSX 10.11 -- can someone please direct me to the correct file. Thanks in advance!

**Comment by eknoes** [comment]
Did you install scholar.py with pip? You have to change the file scholar.py, its the one and only file in this repository.

**Comment by chendaniely** [comment]
does the parser warning affect anything?
I see the warning as well, but I still get (expected) results.

@lenpr @7sam7 what I did was download the `scholar.py` script directly and put it in the same directory as the `*.py` file that's loading the `scholar` module.  Then you can make your changes, and load the module.

to do this, you go to the [scholar.py](https://github.com/ckreibich/scholar.py/blob/master/scholar.py) page, and right click `raw` then `save link as`

**Comment by karen368** [comment]
@eknoes hello, I have installed the scholar.py. But then what I should do? How to change it?Please

**Comment by eknoes** [comment]
@chendaniely No, it doesnt affect anything. 
@karen368 just scroll up to #issuecomment-150510827

**Comment by iamaziz** [comment]
As mentioned above, to get rid of `BeautifulSoup` warning, change [this line](https://github.com/ckreibich/scholar.py/blob/master/scholar.py#L359) of `scholar.py` to:

```self.soup = BeautifulSoup(html, "html.parser")```

**Comment by karen368** [comment]
@iamaziz yes, I have tried, that's ok

**Comment by hemesh-patel** [comment]
I'm using PyCharm and I have the same problem. But I cannot find the scholar.py file. Can anyone help me with where it might be located?

**Comment by distriker** [comment]
Hi @hemesh-patel!
scholar.py is the file that you have downloaded to use it and it's where you have to search `BeautifulSoup(html)` (there is two times) and change to `BeautifulSoup(html, 'html.parser')`, like @someValue and @eknoes said.

**Comment by vext01** [comment]
Same here on OpenBSD-current.

Rather than have people patch locally, can a fix be implemented upstream?

**Comment by fredzannarbor** [comment]
Why can't I install a better parser on my system to get rid of the warning?

**Comment by PapstJL4U** [comment]
@skeerthikumar It did not work for me, but i found another workaround.
Instead of giving BS4 the markup, i gave it the source.
`from bs4 import BeautifulSoup    `
`import urllib.request    `
`url = urllib.request.urlopen(your-url-add)    `
`soup = BeautifulSoup(url, "lxml")    `
and as a test
`print(soup.prettify()[0:1000])`

**Comment by ckreibich** [comment]
Folks, this problem should be resolved as of December 28. (I forgot to leave a version bump for this in the file.) If you still see it, please let me know. Cheers!

**Comment by jalbalah** [comment]
This worked for me:
1) Change Here: `C:/Python34/Lib/site-packages/bs4/__init__.py`, see end of file (last few lines)
2) Change: `soup = BeautifulSoup(sys.stdin)` to `soup = BeautifulSoup(sys.stdin, "html.parser")`
3) Then comment out the warning... It uses `builder_registry.lookup(*features)().is_xml to set markup_type` (around line 181):
```
#warnings.warn(self.NO_PARSER_SPECIFIED_WARNING % dict(
        #    filename=filename,
        #    line_number=line_number,
        #    parser=builder.NAME,
        #    markup_type=markup_type))
```
4) Save and close

**Comment by Jasonwu123** [comment]
`from urllib.request import urlopen
from bs4 import BeautifulSoup

html = urlopen("http://www.pythonscraping.com/exercises/exercise1.html")
bsObj = BeautifulSoup(html.read())
print(bsObj.h1)
`
`
from urllib.request import urlopen
from bs4 import BeautifulSoup

html = urlopen('http://www.pythonscraping.com/exercises/exercise1.html')
bsObj = BeautifulSoup(html,'html.parser')
print(bsObj.h1)`

**Comment by mSafdarAli** [comment]
thanks a lot @someValue
