### ISSUE TITLE
List of papers cited by a paper

### ISSUE THREAD

**Issue by nithishdivakar** [ckreibich/scholar.py#55]

**Comment by willwhitney** [comment]
:+1:

**Comment by cryptid11** [comment]
And the opposite, papers, that cite the paper in object, this would be very good for graph study and discovery, I think it's a very basic feature.

**Comment by maplewizard** [comment]
+1

**Comment by mfiume** [comment]
+1

**Comment by mikeatm** [comment]
Does google scholar provide this information?  does anyone  here have a  sample query that can do this? 
im unable to find any indication that  given a paper i can get what the paper cites.

**Comment by lucabaronti** [comment]
I'm not sure that google scholar provides this information (it would be great btw).
On the other hand, the opposite, as @cryptid11 asked, is supported and it's pretty easy to implement in the current scholar.py implementation.
I've presented an implementation for it in this pull request https://github.com/ckreibich/scholar.py/pull/83

**Comment by arcoyk** [comment]
+1
