### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by PrivateMandella** [ckreibich/scholar.py#68]
When I run this code:
`title = 'correlating equations for laminar and turbulent free convection from a vertical plate'
paper = next(sch.search_pubs_query(title)).fill()`
I get an error that says this:
`File "citation_info.py", line 5, in <module>
    paper = next(sch.search_pubs_query(title)).fill()
  File "/usr/local/lib/python2.7/site-packages/scholarly.py", line 183, in fill
    bibtex = _get_page(self.url_scholarbib)
  File "/usr/local/lib/python2.7/site-packages/scholarly.py", line 62, in _get_page
    img_url = img_url_soup.findAll(alt='scholarly_captcha')[0].get('src')
IndexError: list index out of range
`
"citation_info.py" is the script that calls the two lines of code. Thanks in advance for any help.

**Comment by 2t7** [comment]
Looks like you are using  [scholarly](https://github.com/OrganicIrradiation/scholarly), not scholar.py
--> This issue can be closed

**Comment by PrivateMandella** [comment]
How embarrassing
