### ISSUE TITLE
limitation in number of result of articles.

### ISSUE THREAD

**Issue by floweri** [ckreibich/scholar.py#72]
I want to get all number of articles but it give me only 20 article as a result.
I changed this line too but this limitation is still there:

```
MAX_PAGE_RESULTS = 20 # Current maximum for per-page results
```

**Comment by eknoes** [comment]
See #43 & #44

**Comment by ckreibich** [comment]
That's correct, it's a frequently requested feature and doable (even though it will push you toward query limits faster). I hope I'll get to this in the not too distant future. Thanks to all who have submitted pull requests!
