### ISSUE TITLE
citation option

### ISSUE THREAD

**Issue by guidov** [ckreibich/scholar.py#75]
Does anyone else have problems with --citation option not working anymore?

**Comment by lopespaz** [comment]
Hi, this is related to 503 google error. You will see it setting the log level to 3 at line 214. 

This is the related issue: https://github.com/ckreibich/scholar.py/issues/52.

To workaround, you can install a cookie export plugin, open a google scholar session on your firefox, call the plugin, save the cookies to a file and, finally, tell scholar.py to use this cookie file. 

It worked for me.

[]s.

**Comment by guidov** [comment]
Hi, Thanks

Yes its a cookie issue. I managed to get some code to work using the cookie saved from the browser.

An alternative might be to randomly generate a cookie that conforms with the google scholar platform, but I haven't tried the random cookie option yet.
http://blog.venthur.de/index.php/2010/01/query-google-scholar-using-python/

**Comment by rodrigoSantamaria** [comment]
Hi,
I tried the cookies solution and the 503 error is no longer there, but instead I have an "invalid header" error al log level 3:
```
[ INFO]  requesting settings failed: Invalid header value '__utma=1.414250678.1474558396.1474558396.1474558396.1\r; __utmz=1.1474558396.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)\r; GSP=IN=7e6cc990821af63+54afcd58e3b38df9:LD=en:NR=20:CF=4:NT=1483952016:LM=1483960723:S=lwgefSPUdB2lMq6G\r; APISID=K4dVWQ4RSmxXC1VQ/Af5RWMtQZWWzuyjmL\r; CONSENT=YES+ES.es+20150622-23-0\r; NID=94=OblwF-fKijA6iEztz07OpxtYqVcDVaOvW2Z1VTjs76LNxS9tChrd50a9m7RTrPZbRwdpGOB9t2r43brOfmJDx8Yy2ilCEpx31Wx4OY4rgHZbtUcQ5QbM7kOtv3I40UiV\r; SID=HQT873OgukcCdepRa7p8Fj_2tHOgeLgOkvYWpvg-SE1iyGterUL-sB8oEprHHO7ppDEKIA.\r; HSID=A5Y7_zFd3WPCneMoS\r'
<__main__.SearchScholarQuery object at 0x1027f3110>
```

I have no clue what's going on... any idea?
