### ISSUE TITLE
Queries with counts above 19 come back blank

### ISSUE THREAD

**Issue by stringtheory178** [ckreibich/scholar.py#82]
When I try to do queries with counts over 19 it just goes straight to the next input. What is the reason for this behavior? Does google block queries over 19 results? Alternatively, is it because the script only looks at the first page of results? Is there an easy workaround in this case or would I have to code this functionality myself?

**Comment by ckreibich** [comment]
Yeah, scholar.py currently doesn't support this. Handling this properly will require multi-page results retrieval, for which a ticket already exists. I'm going to go ahead and close this as a duplicate. Thanks!
